### PR TITLE
fix (https://github.com/node-webrtc/node-webrtc-examples/issues/22)

### PR DESCRIPTION
**Pull request by yishengjiang99**
- add actual TURN servers to /lib/IceServers.js to be set in constructor
- moved waitUntilIceGatheringStateComplete from "doOffer" to "applyAnswer"
- send back gathered Ice candidates as response to POST remote-connection end point
-  client.js applies gathered ice candidates from above step to its localPeerConnection

### CODE REVIEW

**Comment by yishengjiang99** [comment]
addresses https://github.com/node-webrtc/node-webrtc-examples/issues/22

**Comment by codersneha3012** [comment]
Hi,

I am trying to setup stun/turn server on my AWS EC2 instance but I am getting the following error:
The server stun:xx.xx.xx.xx:3478 returned an error with code=701:
STUN server address is incompatible.

Can you suggest something?

**Comment by codersneha3012** [comment]
Hi,
waitUntilIceGatheringStateComplete in applyAnswer in webrtcconnection.js is never getting completed and hence it is throwing an error.
Also why have you not created iceCandidate on client and added it on server. In peer to peer system it is also done.

What if remove the timeout on the post remote connection answer, and just return an empty array when no ice can is found - Also if I do this will it solve the issue that it is not getting any icecandidate.

**Comment by those-times** [comment]
Hello,
does this fix work? 
You pass 'rtcIceServers' parameter in one instance of RTCPeerConnection and 'RTCIceServers' to another. RTCPeerConnection should take in 'iceServers' parameter.

**Comment by yishengjiang99** [comment]
> Hello,
> does this fix work?
> You pass 'rtcIceServers' parameter in one instance of RTCPeerConnection and 'RTCIceServers' to another. RTCPeerConnection should take in 'iceServers' parameter.

good eye. i fixed thqt one and deployed to https://v2.grepawk.com/record-audio-video-stream/index.html

and the audio/video is not working for me

**Comment by markandrus** [comment]
Sorry, I cannot accept this.

**Pull request closed without merging**
